id: 1
model:
    arch: fcn16s

data:
    dataset: thigh
    compound: False
    train_split: train
    val_split: val
    test_split: test
    img_rows: 'same'
    img_cols: 'same'
#    path: '/media/jacktang/Work/USYD/Research/2020_ISMRM/dataset/whole'
    path: '~/Documents/Research/2020/ISMRM/dataset'

training:
    train_iters: 200 #200
    batch_size: 4
    patch_size: 256

    cross_entropy_ratio: 0.003
    val_interval: 1 #10
    n_classes: 2
    n_workers: 4
    print_interval: 1
    print_interval_per_batch: False
    augmentations:
      hflip: 0.5 # [0, 1)
      vflip: 0.5 # [0, 1)
      rotate: 180 # [-180, 180]
    optimizer:
        name: 'adam'
        lr: 1.0e-3
        weight_decay: 0.0005
#        momentum: 0.9
    loss:
#        name: 'cross_entropy2d'
        name: dice
        size_average: True
    lr_schedule:
    resume:

test:
    batch_size: 4
    n_workers: 4
    cp_path : '/media/jacktang/Work/USYD/Research/2020_ISMRM/Deep_Muscle_Segmentation/runs/fcn16s/dice/fcn16s_thigh_model_best.pkl'
    save: True
    nifti: